language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=thoughts
after_success:
  - codecov
env:
  - CODECOV_TOKEN="6b1680e1-fc34-4363-82d7-4a8277c85bd2"
