FROM python:3
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD thoughts thoughts

ENV MQ_URL rabbitmq://127.0.0.1:5672
ENV PARSER all
CMD python -m thoughts.parsers run-parsers -q ${MQ_URL} -p ${PARSER}