FROM python:3
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD thoughts thoughts
EXPOSE 8000

ENV API_URL http://api:5000

CMD ["python", "-m", "thoughts.gui", "run-server", "-h", "0.0.0.0"]