FROM python:3
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD thoughts thoughts

ENV DB_URL mongodb://127.0.0.1:27017

CMD python -m thoughts.api run-server -h 0.0.0.0 -d ${DB_URL}